/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.TaskController;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Project;
import model.Task;

public class TaskDialogScreen extends javax.swing.JDialog {

   TaskController controller;
   Project project; 
   
    public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        controller = new TaskController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelToolBar = new javax.swing.JPanel();
        TitleToolBar = new javax.swing.JLabel();
        FundoBotaoSave = new javax.swing.JPanel();
        ToolBarSave = new javax.swing.JLabel();
        Task = new javax.swing.JPanel();
        Nome = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();
        Descricao = new javax.swing.JLabel();
        ScrollDescricao = new javax.swing.JScrollPane();
        CampoDescricao = new javax.swing.JTextArea();
        Prazo = new javax.swing.JLabel();
        Notas = new javax.swing.JLabel();
        ScrollNotas = new javax.swing.JScrollPane();
        CampoNotas = new javax.swing.JTextArea();
        CampoPrazo = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PainelToolBar.setBackground(new java.awt.Color(0, 153, 102));

        TitleToolBar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TitleToolBar.setForeground(new java.awt.Color(255, 255, 255));
        TitleToolBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleToolBar.setText("Tarefa");

        ToolBarSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ToolBarSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check-mark.png"))); // NOI18N
        ToolBarSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToolBarSaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout FundoBotaoSaveLayout = new javax.swing.GroupLayout(FundoBotaoSave);
        FundoBotaoSave.setLayout(FundoBotaoSaveLayout);
        FundoBotaoSaveLayout.setHorizontalGroup(
            FundoBotaoSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FundoBotaoSaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToolBarSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FundoBotaoSaveLayout.setVerticalGroup(
            FundoBotaoSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FundoBotaoSaveLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ToolBarSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout PainelToolBarLayout = new javax.swing.GroupLayout(PainelToolBar);
        PainelToolBar.setLayout(PainelToolBarLayout);
        PainelToolBarLayout.setHorizontalGroup(
            PainelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleToolBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FundoBotaoSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PainelToolBarLayout.setVerticalGroup(
            PainelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelToolBarLayout.createSequentialGroup()
                        .addComponent(TitleToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(PainelToolBarLayout.createSequentialGroup()
                        .addComponent(FundoBotaoSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        Task.setBackground(new java.awt.Color(255, 255, 255));

        Nome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Nome.setText("Nome");

        CampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeActionPerformed(evt);
            }
        });

        Descricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Descricao.setText("Descrição");

        CampoDescricao.setColumns(20);
        CampoDescricao.setRows(5);
        ScrollDescricao.setViewportView(CampoDescricao);

        Prazo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Prazo.setText("Prazo");

        Notas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Notas.setText("Notas");

        CampoNotas.setColumns(20);
        CampoNotas.setRows(5);
        ScrollNotas.setViewportView(CampoNotas);

        CampoPrazo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        javax.swing.GroupLayout TaskLayout = new javax.swing.GroupLayout(Task);
        Task.setLayout(TaskLayout);
        TaskLayout.setHorizontalGroup(
            TaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollNotas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addComponent(ScrollDescricao, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CampoNome)
                    .addComponent(Nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Descricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Prazo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Notas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampoPrazo))
                .addContainerGap())
        );
        TaskLayout.setVerticalGroup(
            TaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Descricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Prazo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Notas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollNotas, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Task, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Task, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeActionPerformed

    private void ToolBarSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToolBarSaveMouseClicked
        // TODO add your handling code here:
        try {
           if(CampoNome.getText().isEmpty() || CampoPrazo.getText().isEmpty()) {
             JOptionPane.showMessageDialog(rootPane, "A tarefa"
                 + " não pode ter nome e/ou prazo vazio!");
           } else {           
             Task task = new Task();
                         
         //codigo correto do de cima
         task.setIdProject(project.getId());
         
         task.setName(CampoNome.getText());
         task.setDescription(CampoDescricao.getText());
         task.setNotes(CampoNotas.getText());
         task.setIsCompleted(false);
         
         SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
         Date deadline = null;
         
         deadline = dateFormat.parse(CampoPrazo.getText());
         task.setDeadline(deadline);
         controller.save(task);
         JOptionPane.showMessageDialog(rootPane, "Tarefa salva com sucesso");
         this.dispose();
           }
         
         } catch (Exception e){
           JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }         
    }//GEN-LAST:event_ToolBarSaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskDialogScreen dialog = new TaskDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CampoDescricao;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JTextArea CampoNotas;
    private javax.swing.JFormattedTextField CampoPrazo;
    private javax.swing.JLabel Descricao;
    private javax.swing.JPanel FundoBotaoSave;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Notas;
    private javax.swing.JPanel PainelToolBar;
    private javax.swing.JLabel Prazo;
    private javax.swing.JScrollPane ScrollDescricao;
    private javax.swing.JScrollPane ScrollNotas;
    private javax.swing.JPanel Task;
    private javax.swing.JLabel TitleToolBar;
    private javax.swing.JLabel ToolBarSave;
    // End of variables declaration//GEN-END:variables

    public void setProject(Project project) {
        this.project = project;
    }



}
